import { useEffect, useRef, useState } from 'react';
import type { RealtimeChannel } from '@supabase/supabase-js';
import { getRealtimeClient } from './supabaseRealtimeClient';

// ── Types ─────────────────────────────────────────────────────────────

/** Stable per-device id for the collab channel — distinguishes two windows
 *  of the same logged-in user (e.g. laptop + phone). Generated lazily and
 *  cached in localStorage. Different from the canvas-sync deviceId; lives
 *  in its own slot so resetting one doesn't disturb the other. */
function getDeviceId(): string {
    const KEY = 'klypix:collab:deviceId';
    let id = localStorage.getItem(KEY);
    if (!id) {
        id = 'cdev_' + Math.random().toString(36).slice(2) + Date.now().toString(36);
        localStorage.setItem(KEY, id);
    }
    return id;
}

/** Stable color per user — deterministic hash → 12-slot palette. Two users
 *  with similar names won't collide because we hash the userId, not the
 *  display name. Picked to be readable on both dark and paper canvases. */
const PEER_COLORS = [
    '#10b981', // emerald
    '#3b82f6', // blue
    '#f59e0b', // amber
    '#ec4899', // pink
    '#8b5cf6', // violet
    '#ef4444', // red
    '#06b6d4', // cyan
    '#84cc16', // lime
    '#f97316', // orange
    '#a855f7', // purple
    '#14b8a6', // teal
    '#eab308', // yellow
];

function colorForUser(userId: string): string {
    let h = 0;
    for (let i = 0; i < userId.length; i++) h = (h * 31 + userId.charCodeAt(i)) | 0;
    return PEER_COLORS[Math.abs(h) % PEER_COLORS.length];
}

/** Public peer shape — what the UI consumes. */
export interface CollabPeer {
    userId: string;
    deviceId: string;
    displayName: string;
    color: string;
    /** When the peer was last seen broadcasting anything. Used to fade
     *  stale entries when a network drop swallows the leave event. */
    lastSeen: number;
    /** Cursor world coords (set in Phase 2). Optional in Phase 1. */
    cursorX?: number;
    cursorY?: number;
}

/** Shape of a single presence-state slot in Supabase's `presence_state` map.
 *  Multiple devices for the same user end up as separate slots — keyed by
 *  presence_ref (auto-generated by the client) under one Supabase user
 *  bucket. We coerce all of that to a flat CollabPeer list. */
interface PresenceRow {
    user_id: string;
    device_id: string;
    display_name: string;
    joined_at: number;
}

// ── Hook ──────────────────────────────────────────────────────────────

export interface UseCanvasCollabArgs {
    /** Blob id this canvas is synced under. Null/undefined = canvas isn't
     *  shared yet, so no channel and no peers. */
    blobId: string | null | undefined;
    /** Current user's id (from useAuth). Required to identify yourself
     *  to other peers. Null = signed out → no collab. */
    userId: string | null | undefined;
    /** Display name shown on peer chips + cursor labels. */
    displayName: string | null | undefined;
    /** Set true when the tab is hidden / canvas mode inactive so we
     *  don't broadcast a "still here" signal for a tab the user has
     *  background-parked. We still RECEIVE updates so the chip count
     *  is fresh when the user comes back. */
    active: boolean;
}

export interface UseCanvasCollabResult {
    /** Other connected users (excludes self). Empty when collab is
     *  inactive (no blob id / signed out / channel not yet joined). */
    peers: CollabPeer[];
    /** True when we've successfully subscribed to the channel. False
     *  during connection or after an error. UI uses this to gray out
     *  the presence strip on flaky networks. */
    connected: boolean;
}

const CHANNEL_PREFIX = 'klypix-canvas-';

/**
 * Phase 1 collab: subscribes to a Supabase Realtime channel keyed by the
 * canvas's blob id and tracks who else is online. No cursors, no ops yet —
 * those land in Phases 2 + 3. The channel name namespaces collab traffic
 * away from the existing blob-sync table subscriptions.
 *
 * Identity model: each peer is uniquely identified by (userId, deviceId).
 * One user on two devices = two peer entries. We tag each with a stable
 * color hash + display name so the UI can render legible chips.
 */
export function useCanvasCollab(args: UseCanvasCollabArgs): UseCanvasCollabResult {
    const { blobId, userId, displayName, active } = args;
    const [peers, setPeers] = useState<CollabPeer[]>([]);
    const [connected, setConnected] = useState(false);
    const channelRef = useRef<RealtimeChannel | null>(null);

    useEffect(() => {
        // Collab requires: a shared canvas (blob id) + a signed-in user.
        if (!blobId || !userId) {
            setPeers([]);
            setConnected(false);
            return;
        }

        const supabase = getRealtimeClient();
        const channelName = `${CHANNEL_PREFIX}${blobId}`;
        const deviceId = getDeviceId();
        const myName = displayName || 'Anonymous';

        // `presence: { key }` keys the presence slot. Using the per-device id
        // (not the user id) means a user with two tabs/devices appears as
        // two separate peers — accurate for the UI ("two of Sally's
        // devices are connected").
        const channel = supabase.channel(channelName, {
            config: {
                presence: { key: deviceId },
                broadcast: { self: false, ack: false },
            },
        });
        channelRef.current = channel;

        const refreshPeers = () => {
            const presenceState = channel.presenceState() as Record<string, PresenceRow[]>;
            const flat: CollabPeer[] = [];
            const now = Date.now();
            for (const slot of Object.values(presenceState)) {
                for (const row of slot) {
                    if (!row || typeof row !== 'object') continue;
                    // Skip self — UI shows OTHER peers; the user already
                    // knows they're here. Self is part of presenceState
                    // because Supabase echoes our own track() back.
                    if (row.user_id === userId && row.device_id === deviceId) continue;
                    flat.push({
                        userId: row.user_id,
                        deviceId: row.device_id,
                        displayName: row.display_name,
                        color: colorForUser(row.user_id),
                        lastSeen: now,
                    });
                }
            }
            setPeers(flat);
        };

        channel
            .on('presence', { event: 'sync' }, refreshPeers)
            .on('presence', { event: 'join' }, refreshPeers)
            .on('presence', { event: 'leave' }, refreshPeers)
            .subscribe(async (status) => {
                if (status === 'SUBSCRIBED') {
                    setConnected(true);
                    // Only broadcast our presence when the tab is active.
                    // Inactive tabs still receive updates so the chip count
                    // is correct when the user returns.
                    if (active) {
                        await channel.track({
                            user_id: userId,
                            device_id: deviceId,
                            display_name: myName,
                            joined_at: Date.now(),
                        } satisfies PresenceRow);
                    }
                } else if (status === 'CHANNEL_ERROR' || status === 'TIMED_OUT' || status === 'CLOSED') {
                    setConnected(false);
                }
            });

        return () => {
            channelRef.current = null;
            // untrack + unsubscribe is wrapped in try/catch because the
            // channel may already be closed (network drop). Either way
            // we want to release the local handle.
            try { channel.untrack(); } catch { /* ignored */ }
            try { supabase.removeChannel(channel); } catch { /* ignored */ }
            setConnected(false);
            setPeers([]);
        };
    }, [blobId, userId, displayName, active]);

    return { peers, connected };
}
