import { useEffect, useRef, useState } from 'react';
import type { RealtimeChannel } from '@supabase/supabase-js';
import { setRealtimeAuth } from './supabaseRealtimeClient';
import { acquireCanvasChannel } from './channelRegistry';

// ── Types ─────────────────────────────────────────────────────────────

/** Stable per-device id for the collab channel — distinguishes two windows
 *  of the same logged-in user (e.g. laptop + phone). Generated lazily and
 *  cached in localStorage. Different from the canvas-sync deviceId; lives
 *  in its own slot so resetting one doesn't disturb the other. */
function getDeviceId(): string {
    const KEY = 'klypix:collab:deviceId';
    let id = localStorage.getItem(KEY);
    if (!id) {
        id = 'cdev_' + Math.random().toString(36).slice(2) + Date.now().toString(36);
        localStorage.setItem(KEY, id);
    }
    return id;
}

/** Stable color per user — deterministic hash → 12-slot palette. Two users
 *  with similar names won't collide because we hash the userId, not the
 *  display name. Picked to be readable on both dark and paper canvases. */
const PEER_COLORS = [
    '#10b981', // emerald
    '#3b82f6', // blue
    '#f59e0b', // amber
    '#ec4899', // pink
    '#8b5cf6', // violet
    '#ef4444', // red
    '#06b6d4', // cyan
    '#84cc16', // lime
    '#f97316', // orange
    '#a855f7', // purple
    '#14b8a6', // teal
    '#eab308', // yellow
];

function colorForUser(userId: string): string {
    let h = 0;
    for (let i = 0; i < userId.length; i++) h = (h * 31 + userId.charCodeAt(i)) | 0;
    return PEER_COLORS[Math.abs(h) % PEER_COLORS.length];
}

/** Public peer shape — what the UI consumes. */
export interface CollabPeer {
    userId: string;
    deviceId: string;
    displayName: string;
    color: string;
    /** When the peer was last seen broadcasting anything. Used to fade
     *  stale entries when a network drop swallows the leave event. */
    lastSeen: number;
    /** Cursor world coords. Null/undefined = cursor is off the canvas
     *  (the peer's mouse left the surface) → render no cursor for them. */
    cursorX?: number;
    cursorY?: number;
    /** When the cursor position was last received. Used to fade out the
     *  remote cursor after a stale window with no updates. */
    cursorAt?: number;
    /** Item ids currently selected on the peer's side — used to draw
     *  colored selection halos. */
    selectionIds?: string[];
    /** Soft lock — the item id the peer is actively editing (text or
     *  any focused field). Null/undefined = peer is not editing.
     *  Lets us block local edit-mode on the same item to prevent
     *  last-write-wins clobbering on concurrent text input. */
    editingItemId?: string | null;
}

/** Shape of a single presence-state slot in Supabase's `presence_state` map.
 *  Multiple devices for the same user end up as separate slots — keyed by
 *  presence_ref (auto-generated by the client) under one Supabase user
 *  bucket. We coerce all of that to a flat CollabPeer list. */
interface PresenceRow {
    // Nullable: presence broadcasts even before auth resolves (provisional
    // identity). device_id is the always-present stable key; user_id fills
    // in when known and is upgraded via the re-track effect.
    user_id: string | null;
    device_id: string;
    display_name: string;
    joined_at: number;
}

// ── Hook ──────────────────────────────────────────────────────────────

export interface UseCanvasCollabArgs {
    /** Blob id this canvas is synced under. Null/undefined = canvas isn't
     *  shared yet, so no channel and no peers. */
    blobId: string | null | undefined;
    /** Current user's id (from useAuth). Required to identify yourself
     *  to other peers. Null = signed out → no collab. */
    userId: string | null | undefined;
    /** Display name shown on peer chips + cursor labels. */
    displayName: string | null | undefined;
    /** Set true when the tab is hidden / canvas mode inactive so we
     *  don't broadcast a "still here" signal for a tab the user has
     *  background-parked. We still RECEIVE updates so the chip count
     *  is fresh when the user comes back. */
    active: boolean;
}

/** Phase 21: ephemeral DM message broadcast on the canvas channel.
 *  Not persisted server-side — durable chat is a follow-up. Messages
 *  exist only for currently-connected peers; a late joiner sees an
 *  empty thread. */
export interface CollabMessage {
    /** Unique per-message id, sender-assigned, used for React keys + dedupe. */
    id: string;
    /** Sender's userId (presence identity). */
    fromUserId: string;
    /** Sender's deviceId (so two devices of the same user are distinguishable). */
    fromDeviceId: string;
    /** Display name as known by the sender at send-time. */
    fromName: string;
    /** Color hash for chat-bubble accent — derived from fromUserId so the
     *  same person stays the same color across cursor + chat + chip. */
    color: string;
    /** Text body. Trimmed + capped client-side to keep broadcasts small. */
    text: string;
    /** Send time (ms epoch). */
    ts: number;
}

export interface UseCanvasCollabResult {
    /** Other connected users (excludes self). Empty when collab is
     *  inactive (no blob id / signed out / channel not yet joined). */
    peers: CollabPeer[];
    /** True when we've successfully subscribed to the channel. False
     *  during connection or after an error. UI uses this to gray out
     *  the presence strip on flaky networks. */
    connected: boolean;
    /** Publish this device's cursor position in canvas world coords.
     *  Throttled to ~30Hz internally — callers can fire on every
     *  pointermove. Pass null to clear (cursor left the canvas). */
    publishCursor: (world: { x: number; y: number } | null) => void;
    /** Publish this device's current selection so peers can draw halos.
     *  Throttled to ~10Hz — selection changes are far less frequent
     *  than cursor moves so we don't need cursor-grade rates. */
    publishSelection: (selectionIds: string[]) => void;
    /** Phase 23.x: broadcast which item this device is actively editing
     *  (text field focus, etc.). Peers use it to soft-lock their UI on
     *  that item — no concurrent typing means no last-write-wins
     *  clobbering on `text` patches. Pass null to clear the lock when
     *  the user blurs / finishes editing. State changes infrequently
     *  (once per focus/blur) so no throttle needed. */
    publishEditingItem: (itemId: string | null) => void;
    /** Phase 21: messages from peers (excludes own — we keep an optimistic
     *  echo via the same `messages` slot when we call sendMessage so the
     *  UI gets instant feedback). Most recent last. Capped to last 200 in
     *  memory; old ones drop off. */
    messages: CollabMessage[];
    /** Phase 21: send a DM-style message to all connected peers. Returns
     *  the message we just broadcast so callers can render it optimistically
     *  even if they don't read `messages` directly. Returns null when the
     *  channel isn't connected (caller can show a "still connecting" hint). */
    sendMessage: (text: string) => CollabMessage | null;
}

/**
 * Phase 1 collab: subscribes (via the shared channelRegistry, post-Phase 14)
 * to a Supabase Realtime channel keyed by the canvas's blob id and tracks
 * who else is online. Cursors + ops + assets all share that same channel —
 * the registry guarantees a single subscription so broadcasts hit every
 * listener consistently (the 3-channel split before Phase 14 was the root
 * cause of items not syncing across PCs in the real two-PC test).
 *
 * Identity model: each peer is uniquely identified by (userId, deviceId).
 * One user on two devices = two peer entries. We tag each with a stable
 * color hash + display name so the UI can render legible chips.
 */
// Throttle limits — keep cursor publishes well under Supabase Realtime's
// per-second cap (configured 30 in supabaseRealtimeClient.ts). 33ms = 30Hz
// for cursor; 100ms = 10Hz for selection (changes much less frequently).
const CURSOR_THROTTLE_MS = 33;
const SELECTION_THROTTLE_MS = 100;
// Drop a remote cursor after this much silence — covers tab-park, mid-
// network drops, etc. Channel-leave events handle clean exits; this is
// the safety net for unclean ones.
const CURSOR_STALE_MS = 5000;
// 2026-05-28 soft-lock TTL: a peer re-broadcasts its editing item every
// ~5s (heartbeat). If we haven't heard a refresh in this window, the lock
// is considered stale (their blur event was lost, or they navigated away
// without clearing it) and we release it locally so the item doesn't stay
// permanently locked. Must be > 2x the 5s heartbeat to tolerate one miss.
const EDITING_STALE_MS = 12000;
const EDITING_HEARTBEAT_MS = 5000;

const MESSAGE_MAX_TEXT = 2000;
const MESSAGE_BUFFER_MAX = 200;

export function useCanvasCollab(args: UseCanvasCollabArgs): UseCanvasCollabResult {
    const { blobId, userId, displayName, active } = args;
    const [peers, setPeers] = useState<CollabPeer[]>([]);
    const [connected, setConnected] = useState(false);
    const [messages, setMessages] = useState<CollabMessage[]>([]);
    const channelRef = useRef<RealtimeChannel | null>(null);
    // 2026-05-28 presence-race fix: hold the latest displayName in a ref so
    // track() always broadcasts the current name WITHOUT putting displayName
    // in the main effect's dep array. Previously displayName WAS a dep, so a
    // name that resolved a tick after userId tore down + re-acquired the
    // channel (track→untrack→track FLAP) — peers saw the user blink out then
    // back in, and on the owner's PC the chip often never settled. Now the
    // channel lifecycle depends only on [blobId, userId, active]; a separate
    // effect re-calls track() when the name changes or the connection
    // (re)establishes.
    const nameRef = useRef(displayName);
    nameRef.current = displayName;
    // Throttle state: last-publish times + queued payloads. The published
    // value is always the freshest one — partial flushes drop intermediate
    // positions, which is what we want for cursor motion.
    const cursorLastPublishRef = useRef(0);
    const cursorQueuedRef = useRef<{ x: number; y: number } | null | undefined>(undefined);
    const cursorTimerRef = useRef<number | null>(null);
    const selectionLastPublishRef = useRef(0);
    const selectionQueuedRef = useRef<string[] | null>(null);
    const selectionTimerRef = useRef<number | null>(null);

    // Dev-only ghost peer for UI verification on a single machine. Set
    // localStorage['klypix:devCollabGhost'] = '1' (or a comma-separated
    // list of display names) in the renderer console to inject one or
    // more synthetic peers into the chip strip. Ignored in normal use —
    // no real channel traffic, no telemetry.
    //
    // Per-name dismiss state lives in localStorage['klypix:devCollabGhost:hidden']
    // as a comma-joined list of userIds. The "Hide" button in the peer
    // popover writes here so the user can dismiss specific ghosts from
    // the UI without nuking the whole devCollabGhost setting.
    const [ghostHideTick, setGhostHideTick] = useState(0);
    const ghostPeers: CollabPeer[] = (() => {
        try {
            const raw = localStorage.getItem('klypix:devCollabGhost');
            if (!raw) return [];
            const hiddenRaw = localStorage.getItem('klypix:devCollabGhost:hidden') || '';
            const hidden = new Set(hiddenRaw.split(',').filter(Boolean));
            const names = raw === '1' ? ['Ghost Peer'] : raw.split(',').map(s => s.trim()).filter(Boolean);
            return names
                .map((name, i) => ({
                    userId: `ghost_${i}`,
                    deviceId: `ghost_${i}_dev`,
                    displayName: name,
                    color: colorForUser(`ghost_${i}`),
                    lastSeen: Date.now(),
                }))
                .filter(p => !hidden.has(p.userId));
        } catch {
            return [];
        }
    })();
    // Force re-evaluation of ghostPeers when the dismiss list changes.
    void ghostHideTick;
    // Listen for an in-app event so the "Hide" button can trigger a
    // re-render without needing a full reload.
    useEffect(() => {
        const onHide = () => setGhostHideTick((t) => t + 1);
        window.addEventListener('klypix:devCollabGhost:hidden-changed', onHide);
        return () => window.removeEventListener('klypix:devCollabGhost:hidden-changed', onHide);
    }, []);

    useEffect(() => {
        // 2026-05-28 collab diagnostics: surface the gate decision so the
        // user can SEE why presence/cursor isn't running on this PC. The
        // most common silent failure was userId being null (auth not yet
        // restored from DPAPI) — useOpSync would still run (only needs
        // blobId) but useCanvasCollab would silently exit, leaving the
        // user with no chips, no cursors, and no obvious cause.
        console.log(`[collab] effect: blobId=${blobId ? blobId.slice(0, 8) + '…' : 'null'} userId=${userId ? userId.slice(0, 8) + '…' : 'null'} displayName=${displayName ?? 'null'} active=${active}`);
        // 2026-05-31 BEST-IN-CLASS presence: gate ONLY on blobId, NOT userId.
        //
        // Old behavior gated on userId too, so the moment auth.user.id was
        // null/lagging (which happens routinely — renderer auth resolves a
        // tick after the canvas mounts, and can desync from the main-process
        // session) presence shut OFF entirely: no chips, no cursors — even
        // though op-sync (which needs only blobId) kept working. That split
        // is exactly why "edits sync but I see no one" kept happening.
        //
        // Figma/Linear model: presence is keyed on a STABLE deviceId that
        // always exists; the real userId + display name are layered on when
        // known and UPGRADED via the re-track effect below when auth
        // resolves. You appear to peers immediately (as yourself if known,
        // provisionally otherwise) and your name fills in a beat later.
        // Presence is never fully disabled while the canvas is open.
        if (!blobId) {
            console.warn('[collab] DISABLED — no blobId (canvas not shared yet)');
            setPeers([]);
            setConnected(false);
            setMessages([]);
            return;
        }

        const myName = nameRef.current || displayName || 'Guest';

        // Phase 12: hand the current Supabase access token to the Realtime
        // client so it can authenticate channel joins. Required once the
        // server-side channel policy flips to `private: true` (until then
        // it's a no-op for the channel but still primes the connection).
        (async () => {
            try {
                const electronAuth: any = (window as any).electron?.auth;
                const res = await electronAuth?.getAccessToken?.();
                setRealtimeAuth(res?.token ?? null);
            } catch { /* signed out / IPC missing → leave unauthenticated */ }
        })();

        // Phase 21+: hydrate persistent DM history. Late joiners now see
        // the conversation that happened before they opened the canvas;
        // returning users see their own past messages. Best-effort —
        // missing table / migration returns [] gracefully.
        (async () => {
            const cloud: any = (window as any).electron?.cloud;
            if (!cloud?.listMessages) return;
            try {
                const rows: Array<{ id: string; text: string; created_at: string; author_id: string; author_name: string | null; author_email: string | null }> = await cloud.listMessages({ blobId, limit: 200 });
                if (!Array.isArray(rows)) return;
                // Reverse: server returns newest-first; UI wants oldest-first
                // (most-recent at the bottom).
                const restored: CollabMessage[] = rows.slice().reverse().map((r) => ({
                    id: 'srv_' + r.id,
                    fromUserId: r.author_id,
                    fromDeviceId: 'server',
                    fromName: r.author_name || r.author_email || 'User',
                    color: colorForUser(r.author_id),
                    text: r.text.slice(0, MESSAGE_MAX_TEXT),
                    ts: new Date(r.created_at).getTime() || Date.now(),
                }));
                setMessages(prev => {
                    // Merge: keep any locally-buffered messages that aren't
                    // already in the server list (shouldn't happen on a
                    // fresh mount, but defensive against a race).
                    const seen = new Set(restored.map(m => m.id));
                    const live = prev.filter(m => !seen.has(m.id));
                    const merged = restored.concat(live);
                    return merged.length > MESSAGE_BUFFER_MAX ? merged.slice(merged.length - MESSAGE_BUFFER_MAX) : merged;
                });
            } catch { /* fall back to ephemeral-only behavior */ }
        })();

        // Phase 14: acquire the shared canvas channel via the registry.
        // useOpSync + useAssetSync use the SAME channel via the same
        // registry call, so broadcasts hit one shared subscription
        // instead of competing across three channel objects.
        let cancelled = false;
        const onStatus = (status: string) => {
            if (cancelled) return;
            if (status === 'SUBSCRIBED') {
                setConnected(true);
                // Only broadcast our presence when the tab is active.
                if (active) {
                    const trackName = nameRef.current || displayName || 'Guest';
                    console.log(`[collab] channel SUBSCRIBED — track() as ${trackName} (user=${userId ? userId.slice(0, 8) + '…' : 'provisional'}) on device ${deviceId.slice(0, 12)}…`);
                    void channel.track({
                        user_id: userId ?? null,
                        device_id: deviceId,
                        display_name: trackName,
                        joined_at: Date.now(),
                    } satisfies PresenceRow);
                } else {
                    console.log(`[collab] channel SUBSCRIBED but active=false → NOT tracking presence (background tab?)`);
                }
            } else if (status === 'CHANNEL_ERROR' || status === 'TIMED_OUT' || status === 'CLOSED') {
                console.warn(`[collab] channel status: ${status}`);
                setConnected(false);
            }
        };
        const acquired = acquireCanvasChannel(blobId, onStatus);
        const channel = acquired.channel;
        const deviceId = acquired.deviceId;
        channelRef.current = channel;

        // Per-device ephemeral state (cursor + selection) accumulated from
        // broadcast events. NOT in React state directly because cursor updates
        // arrive at ~30Hz and we want a single coalesced render. Stored on a
        // Map, then merged into peers via setPeers on each presence change OR
        // broadcast tick (rAF-coalesced below).
        const ephemeralRef = new Map<string, { cursorX?: number; cursorY?: number; cursorAt?: number; selectionIds?: string[]; editingItemId?: string | null; editingAt?: number }>();
        let renderScheduled = false;
        const scheduleRender = () => {
            if (renderScheduled) return;
            renderScheduled = true;
            requestAnimationFrame(() => {
                renderScheduled = false;
                computeAndSet();
            });
        };

        const computeAndSet = () => {
            if (cancelled) return;
            const presenceState = channel.presenceState() as Record<string, PresenceRow[]>;
            const flat: CollabPeer[] = [];
            const now = Date.now();
            for (const slot of Object.values(presenceState)) {
                for (const row of slot) {
                    if (!row || typeof row !== 'object') continue;
                    // Skip self by DEVICE id — the always-present stable key.
                    // (Was also matching user_id, but user_id can now be null
                    // during the provisional window; device_id alone is the
                    // reliable self-identifier.)
                    if (row.device_id === deviceId) continue;
                    const eph = ephemeralRef.get(row.device_id);
                    // Drop stale cursors so a peer that stopped moving doesn't
                    // leave their cursor floating forever after a network drop.
                    const cursorFresh = eph?.cursorAt && (now - eph.cursorAt) < CURSOR_STALE_MS;
                    // Soft-lock TTL: release a peer's lock if we haven't heard
                    // a heartbeat refresh within EDITING_STALE_MS (their blur
                    // was lost / they wandered off). Prevents a permanent
                    // phantom lock on an item nobody is editing anymore.
                    const editingFresh = eph?.editingAt != null && (now - eph.editingAt) < EDITING_STALE_MS;
                    // Stable identity: prefer the real userId, fall back to the
                    // deviceId so color + key are stable even for a peer still
                    // in the provisional (pre-auth) window.
                    const peerIdentity = row.user_id ?? row.device_id;
                    flat.push({
                        userId: peerIdentity,
                        deviceId: row.device_id,
                        displayName: row.display_name,
                        color: colorForUser(peerIdentity),
                        lastSeen: now,
                        cursorX: cursorFresh ? eph?.cursorX : undefined,
                        cursorY: cursorFresh ? eph?.cursorY : undefined,
                        cursorAt: cursorFresh ? eph?.cursorAt : undefined,
                        selectionIds: eph?.selectionIds,
                        editingItemId: editingFresh ? (eph?.editingItemId ?? null) : null,
                    });
                }
            }
            // Clean up ephemeral entries for devices no longer in presence.
            const liveDeviceIds = new Set(Object.values(presenceState).flat().map((r: any) => r?.device_id).filter(Boolean));
            for (const k of Array.from(ephemeralRef.keys())) {
                if (!liveDeviceIds.has(k)) ephemeralRef.delete(k);
            }
            // 2026-05-28 diagnostics: log peer-count changes so the user
            // can see in DevTools when presence_state is/isn't getting
            // populated by remote track() calls.
            if (flat.length > 0) {
                console.log(`[collab] peers=${flat.length}:`, flat.map(p => `${p.displayName}(${p.deviceId.slice(0, 8)}…)`).join(', '));
            }
            setPeers(flat);
        };
        const refreshPeers = computeAndSet;

        channel
            .on('presence', { event: 'sync' }, refreshPeers)
            .on('presence', { event: 'join' }, refreshPeers)
            .on('presence', { event: 'leave' }, refreshPeers)
            // Cursor broadcast — sent ~30Hz max per peer. Payload carries the
            // sender's device id so we can attribute it; null x/y means
            // "cursor left the canvas" → hide the remote cursor.
            .on('broadcast', { event: 'cursor' }, (msg) => {
                if (cancelled) return;
                const p = (msg as any)?.payload;
                if (!p || typeof p.device_id !== 'string') return;
                if (p.device_id === deviceId) return; // ignore echoes (self:false already, but defensive)
                const prev = ephemeralRef.get(p.device_id) || {};
                if (p.x == null || p.y == null) {
                    // Cursor left the canvas.
                    ephemeralRef.set(p.device_id, { ...prev, cursorX: undefined, cursorY: undefined, cursorAt: undefined });
                } else {
                    ephemeralRef.set(p.device_id, { ...prev, cursorX: p.x, cursorY: p.y, cursorAt: Date.now() });
                }
                // Phase 15: dev-only inbound cursor log.
                if (localStorage.getItem('klypix:debugCursor') === '1') {
                    if (p.x == null || p.y == null) {
                        console.log('[cursor.in]', p.device_id.slice(0, 10), 'left');
                    } else {
                        console.log('[cursor.in]', p.device_id.slice(0, 10), { x: p.x.toFixed(1), y: p.y.toFixed(1) });
                    }
                }
                scheduleRender();
            })
            .on('broadcast', { event: 'selection' }, (msg) => {
                if (cancelled) return;
                const p = (msg as any)?.payload;
                if (!p || typeof p.device_id !== 'string') return;
                if (p.device_id === deviceId) return;
                const prev = ephemeralRef.get(p.device_id) || {};
                ephemeralRef.set(p.device_id, { ...prev, selectionIds: Array.isArray(p.ids) ? p.ids : [] });
                scheduleRender();
            })
            // Phase 23.x: soft-lock signal — peer is actively editing a
            // specific item. Locally we'll block our own SET_EDITING on
            // the same id so concurrent typing can't race the patch.
            .on('broadcast', { event: 'editing' }, (msg) => {
                if (cancelled) return;
                const p = (msg as any)?.payload;
                if (!p || typeof p.device_id !== 'string') return;
                if (p.device_id === deviceId) return;
                const prev = ephemeralRef.get(p.device_id) || {};
                const next = typeof p.item_id === 'string' ? p.item_id : null;
                ephemeralRef.set(p.device_id, { ...prev, editingItemId: next, editingAt: Date.now() });
                scheduleRender();
            })
            // Phase 21: per-canvas DM. Ephemeral broadcast-only; no server
            // persistence. Accepts only well-shaped payloads to keep this
            // from being a vector for noise.
            .on('broadcast', { event: 'dm.message' }, (msg) => {
                if (cancelled) return;
                const p = (msg as any)?.payload;
                if (!p
                    || typeof p.id !== 'string'
                    || typeof p.from_user_id !== 'string'
                    || typeof p.from_device_id !== 'string'
                    || typeof p.text !== 'string'
                    || typeof p.ts !== 'number') return;
                if (p.from_device_id === deviceId) return; // own echo (already added optimistically)
                const next: CollabMessage = {
                    id: p.id,
                    fromUserId: p.from_user_id,
                    fromDeviceId: p.from_device_id,
                    fromName: typeof p.from_name === 'string' ? p.from_name : 'Unknown',
                    color: colorForUser(p.from_user_id),
                    text: p.text.slice(0, MESSAGE_MAX_TEXT),
                    ts: p.ts,
                };
                setMessages(prev => {
                    // Dedupe by id (safety net for double-deliveries).
                    if (prev.some(m => m.id === next.id)) return prev;
                    const out = prev.concat(next);
                    return out.length > MESSAGE_BUFFER_MAX ? out.slice(out.length - MESSAGE_BUFFER_MAX) : out;
                });
            });
        // Channel subscribe happens once inside acquireCanvasChannel —
        // status changes flow through onStatus above.

        // Periodic stale-cursor sweep: every 2s, force a recompute so cursors
        // older than CURSOR_STALE_MS get filtered out. Without this, a peer
        // whose tab drops the network would leave their cursor frozen
        // mid-canvas indefinitely until either the channel emits a leave
        // event or new presence arrives.
        const staleInterval = window.setInterval(() => {
            // Only sweep if there's at least one peer with a cursor — saves
            // setPeers churn for the common solo case.
            let needsSweep = false;
            const now = Date.now();
            for (const eph of ephemeralRef.values()) {
                if (eph.cursorAt && (now - eph.cursorAt) >= CURSOR_STALE_MS) { needsSweep = true; break; }
                // Also recompute when a soft-lock has gone stale so the
                // RemoteLockBadge + SET_PEER_LOCKS clear without waiting for
                // a presence event.
                if (eph.editingAt != null && eph.editingItemId && (now - eph.editingAt) >= EDITING_STALE_MS) { needsSweep = true; break; }
            }
            if (needsSweep) computeAndSet();
        }, 2000);

        // 2026-05-28 presence heartbeat: re-track every 15s while active so a
        // peer that missed a presence sync (transient socket blip) is
        // re-announced, and Supabase's presence keepalive stays warm. Cheap
        // — one track() per 15s is far under the 30 events/sec channel cap.
        const heartbeatInterval = window.setInterval(() => {
            if (cancelled || !active) return;
            const ch = channelRef.current;
            if (!ch) return;
            void ch.track({
                user_id: userId ?? null,
                device_id: deviceId,
                display_name: nameRef.current || displayName || 'Guest',
                joined_at: Date.now(),
            } satisfies PresenceRow);
        }, 15000);

        return () => {
            cancelled = true;
            channelRef.current = null;
            window.clearInterval(staleInterval);
            window.clearInterval(heartbeatInterval);
            // untrack just our presence (other hooks on this same channel
            // may still need it alive). Then release our refCount; the
            // registry tears down the channel when refCount hits 0.
            try { channel.untrack(); } catch { /* ignored */ }
            acquired.release();
            setConnected(false);
            setPeers([]);
        };
        // 2026-05-31: userId AND displayName both REMOVED from deps. The
        // channel lifecycle now depends only on [blobId, active] — neither
        // identity field tears the channel down (which would also blip the
        // SHARED sync channel). Identity (userId + name) is announced
        // immediately with whatever's known, then UPGRADED in-place by the
        // re-track effect below when auth resolves — no teardown, no flap.
    }, [blobId, active]);

    // 2026-05-31 presence identity upgrade: re-broadcast presence whenever
    // the userId or display name resolves/changes, or the connection
    // (re)establishes. The main effect's initial track() may have fired with
    // a null userId / provisional name (auth not yet resolved); this re-track
    // upgrades the SAME presence slot in-place (reusing channelRef) the moment
    // real identity lands — so peers see "Guest" flip to the real name, and
    // the row gains its real user_id, without any channel churn.
    useEffect(() => {
        if (!connected || !active) return;
        const ch = channelRef.current;
        if (!ch) return;
        void ch.track({
            user_id: userId ?? null,
            device_id: getDeviceId(),
            display_name: displayName || 'Guest',
            joined_at: Date.now(),
        } satisfies PresenceRow);
    }, [displayName, connected, userId, active]);

    // Throttled cursor publisher. Callers can fire on every pointermove;
    // we coalesce to at most one broadcast per CURSOR_THROTTLE_MS using
    // a leading-edge + trailing-flush pattern (fire immediately on first
    // call, queue the rest, flush once after the throttle window).
    const publishCursor = (world: { x: number; y: number } | null): void => {
        const channel = channelRef.current;
        if (!channel) return;
        cursorQueuedRef.current = world;
        const now = Date.now();
        const sinceLast = now - cursorLastPublishRef.current;
        if (sinceLast >= CURSOR_THROTTLE_MS) {
            // Leading edge: send immediately.
            cursorLastPublishRef.current = now;
            const payload = cursorQueuedRef.current;
            cursorQueuedRef.current = undefined;
            const deviceId = getDeviceId();
            channel.send({
                type: 'broadcast',
                event: 'cursor',
                payload: { device_id: deviceId, x: payload?.x ?? null, y: payload?.y ?? null },
            });
            // Phase 15: dev-only outbound cursor log. Enable with
            // localStorage['klypix:debugCursor'] = '1'. Logs the world coord
            // we just broadcast so the user can verify on the OTHER PC's
            // dev console (where Phase 15 logs the received value).
            if (localStorage.getItem('klypix:debugCursor') === '1') {
                console.log('[cursor.out]', payload === null ? 'null' : { x: payload.x.toFixed(1), y: payload.y.toFixed(1) });
            }
            return;
        }
        // Trailing flush: schedule a single timer to send the latest queued
        // value at the end of this throttle window.
        if (cursorTimerRef.current != null) return;
        cursorTimerRef.current = window.setTimeout(() => {
            cursorTimerRef.current = null;
            const ch = channelRef.current;
            if (!ch) return;
            cursorLastPublishRef.current = Date.now();
            const payload = cursorQueuedRef.current;
            cursorQueuedRef.current = undefined;
            const deviceId = getDeviceId();
            ch.send({
                type: 'broadcast',
                event: 'cursor',
                payload: { device_id: deviceId, x: payload?.x ?? null, y: payload?.y ?? null },
            });
        }, CURSOR_THROTTLE_MS - sinceLast);
    };

    // Phase 23.x: soft-lock publisher — sent on edit-start / blur. State
    // changes once per focus, so no throttle. The receiver caches the
    // value in ephemeralRef and the canvas-level effect builds a lock
    // map from it. Cleared automatically on channel teardown via
    // presence-leave (eph entry deleted in computeAndSet cleanup).
    const lastPublishedEditingRef = useRef<string | null>(null);
    const lastEditingSendAtRef = useRef(0);
    const publishEditingItem = (itemId: string | null): void => {
        const now = Date.now();
        // Dedupe identical values UNLESS this is a heartbeat: a non-null
        // value re-sends every EDITING_HEARTBEAT_MS so the peer's TTL stays
        // refreshed (a lost blur otherwise strands a phantom lock). Null
        // (blur) always sends immediately on change.
        const changed = lastPublishedEditingRef.current !== itemId;
        const heartbeatDue = itemId != null && (now - lastEditingSendAtRef.current) >= EDITING_HEARTBEAT_MS;
        if (!changed && !heartbeatDue) return;
        lastPublishedEditingRef.current = itemId;
        lastEditingSendAtRef.current = now;
        const channel = channelRef.current;
        if (!channel) return;
        const deviceId = getDeviceId();
        channel.send({
            type: 'broadcast',
            event: 'editing',
            payload: { device_id: deviceId, item_id: itemId },
        });
    };

    const publishSelection = (selectionIds: string[]): void => {
        const channel = channelRef.current;
        if (!channel) return;
        selectionQueuedRef.current = selectionIds;
        const now = Date.now();
        const sinceLast = now - selectionLastPublishRef.current;
        if (sinceLast >= SELECTION_THROTTLE_MS) {
            selectionLastPublishRef.current = now;
            const ids = selectionQueuedRef.current ?? [];
            selectionQueuedRef.current = null;
            const deviceId = getDeviceId();
            channel.send({
                type: 'broadcast',
                event: 'selection',
                payload: { device_id: deviceId, ids },
            });
            return;
        }
        if (selectionTimerRef.current != null) return;
        selectionTimerRef.current = window.setTimeout(() => {
            selectionTimerRef.current = null;
            const ch = channelRef.current;
            if (!ch) return;
            selectionLastPublishRef.current = Date.now();
            const ids = selectionQueuedRef.current ?? [];
            selectionQueuedRef.current = null;
            const deviceId = getDeviceId();
            ch.send({
                type: 'broadcast',
                event: 'selection',
                payload: { device_id: deviceId, ids },
            });
        }, SELECTION_THROTTLE_MS - sinceLast);
    };

    const sendMessage = (text: string): CollabMessage | null => {
        const channel = channelRef.current;
        const trimmed = text.trim();
        if (!trimmed) return null;
        if (!channel) return null;
        if (!userId) return null;
        const deviceId = getDeviceId();
        const out: CollabMessage = {
            id: 'm_' + Math.random().toString(36).slice(2) + Date.now().toString(36),
            fromUserId: userId,
            fromDeviceId: deviceId,
            fromName: displayName || 'You',
            color: colorForUser(userId),
            text: trimmed.slice(0, MESSAGE_MAX_TEXT),
            ts: Date.now(),
        };
        // Optimistic local append — own messages won't echo back because
        // broadcast.self:false on the channel.
        setMessages(prev => {
            const next = prev.concat(out);
            return next.length > MESSAGE_BUFFER_MAX ? next.slice(next.length - MESSAGE_BUFFER_MAX) : next;
        });
        try {
            channel.send({
                type: 'broadcast',
                event: 'dm.message',
                payload: {
                    id: out.id,
                    from_user_id: out.fromUserId,
                    from_device_id: out.fromDeviceId,
                    from_name: out.fromName,
                    text: out.text,
                    ts: out.ts,
                },
            });
        } catch { /* best-effort; UI shows the optimistic copy regardless */ }
        // Phase 21+: persist to canvas_messages so this message survives
        // reload and reaches late joiners. Fire-and-forget — the broadcast
        // already happened so peers got the live update; persistence is
        // a follow-up for durability. Skips silently when the migration
        // hasn't been applied (the handler returns gracefully).
        if (blobId) {
            const cloud: any = (window as any).electron?.cloud;
            if (cloud?.appendMessage) {
                void cloud.appendMessage({ blobId, text: out.text }).catch(() => { /* swallow */ });
            }
        }
        return out;
    };

    return {
        // Ghost peers are visual-only; show them alongside whatever's
        // actually on the channel. When ghost-only (no real channel),
        // we report connected=true so the UI shows them at full opacity
        // — accurate for testing the rendered look, since "connected"
        // dimming would otherwise make every ghost chip half-faded.
        peers: ghostPeers.length > 0 ? [...peers, ...ghostPeers] : peers,
        connected: connected || ghostPeers.length > 0,
        publishCursor,
        publishSelection,
        publishEditingItem,
        messages,
        sendMessage,
    };
}
