import { useEffect, useRef, useState } from 'react';
import type { RealtimeChannel } from '@supabase/supabase-js';
import { getRealtimeClient, setRealtimeAuth } from './supabaseRealtimeClient';

// ── Types ─────────────────────────────────────────────────────────────

/** Stable per-device id for the collab channel — distinguishes two windows
 *  of the same logged-in user (e.g. laptop + phone). Generated lazily and
 *  cached in localStorage. Different from the canvas-sync deviceId; lives
 *  in its own slot so resetting one doesn't disturb the other. */
function getDeviceId(): string {
    const KEY = 'klypix:collab:deviceId';
    let id = localStorage.getItem(KEY);
    if (!id) {
        id = 'cdev_' + Math.random().toString(36).slice(2) + Date.now().toString(36);
        localStorage.setItem(KEY, id);
    }
    return id;
}

/** Stable color per user — deterministic hash → 12-slot palette. Two users
 *  with similar names won't collide because we hash the userId, not the
 *  display name. Picked to be readable on both dark and paper canvases. */
const PEER_COLORS = [
    '#10b981', // emerald
    '#3b82f6', // blue
    '#f59e0b', // amber
    '#ec4899', // pink
    '#8b5cf6', // violet
    '#ef4444', // red
    '#06b6d4', // cyan
    '#84cc16', // lime
    '#f97316', // orange
    '#a855f7', // purple
    '#14b8a6', // teal
    '#eab308', // yellow
];

function colorForUser(userId: string): string {
    let h = 0;
    for (let i = 0; i < userId.length; i++) h = (h * 31 + userId.charCodeAt(i)) | 0;
    return PEER_COLORS[Math.abs(h) % PEER_COLORS.length];
}

/** Public peer shape — what the UI consumes. */
export interface CollabPeer {
    userId: string;
    deviceId: string;
    displayName: string;
    color: string;
    /** When the peer was last seen broadcasting anything. Used to fade
     *  stale entries when a network drop swallows the leave event. */
    lastSeen: number;
    /** Cursor world coords. Null/undefined = cursor is off the canvas
     *  (the peer's mouse left the surface) → render no cursor for them. */
    cursorX?: number;
    cursorY?: number;
    /** When the cursor position was last received. Used to fade out the
     *  remote cursor after a stale window with no updates. */
    cursorAt?: number;
    /** Item ids currently selected on the peer's side — used to draw
     *  colored selection halos. */
    selectionIds?: string[];
}

/** Shape of a single presence-state slot in Supabase's `presence_state` map.
 *  Multiple devices for the same user end up as separate slots — keyed by
 *  presence_ref (auto-generated by the client) under one Supabase user
 *  bucket. We coerce all of that to a flat CollabPeer list. */
interface PresenceRow {
    user_id: string;
    device_id: string;
    display_name: string;
    joined_at: number;
}

// ── Hook ──────────────────────────────────────────────────────────────

export interface UseCanvasCollabArgs {
    /** Blob id this canvas is synced under. Null/undefined = canvas isn't
     *  shared yet, so no channel and no peers. */
    blobId: string | null | undefined;
    /** Current user's id (from useAuth). Required to identify yourself
     *  to other peers. Null = signed out → no collab. */
    userId: string | null | undefined;
    /** Display name shown on peer chips + cursor labels. */
    displayName: string | null | undefined;
    /** Set true when the tab is hidden / canvas mode inactive so we
     *  don't broadcast a "still here" signal for a tab the user has
     *  background-parked. We still RECEIVE updates so the chip count
     *  is fresh when the user comes back. */
    active: boolean;
}

export interface UseCanvasCollabResult {
    /** Other connected users (excludes self). Empty when collab is
     *  inactive (no blob id / signed out / channel not yet joined). */
    peers: CollabPeer[];
    /** True when we've successfully subscribed to the channel. False
     *  during connection or after an error. UI uses this to gray out
     *  the presence strip on flaky networks. */
    connected: boolean;
    /** Publish this device's cursor position in canvas world coords.
     *  Throttled to ~30Hz internally — callers can fire on every
     *  pointermove. Pass null to clear (cursor left the canvas). */
    publishCursor: (world: { x: number; y: number } | null) => void;
    /** Publish this device's current selection so peers can draw halos.
     *  Throttled to ~10Hz — selection changes are far less frequent
     *  than cursor moves so we don't need cursor-grade rates. */
    publishSelection: (selectionIds: string[]) => void;
}

const CHANNEL_PREFIX = 'klypix-canvas-';

/**
 * Phase 1 collab: subscribes to a Supabase Realtime channel keyed by the
 * canvas's blob id and tracks who else is online. No cursors, no ops yet —
 * those land in Phases 2 + 3. The channel name namespaces collab traffic
 * away from the existing blob-sync table subscriptions.
 *
 * Identity model: each peer is uniquely identified by (userId, deviceId).
 * One user on two devices = two peer entries. We tag each with a stable
 * color hash + display name so the UI can render legible chips.
 */
// Throttle limits — keep cursor publishes well under Supabase Realtime's
// per-second cap (configured 30 in supabaseRealtimeClient.ts). 33ms = 30Hz
// for cursor; 100ms = 10Hz for selection (changes much less frequently).
const CURSOR_THROTTLE_MS = 33;
const SELECTION_THROTTLE_MS = 100;
// Drop a remote cursor after this much silence — covers tab-park, mid-
// network drops, etc. Channel-leave events handle clean exits; this is
// the safety net for unclean ones.
const CURSOR_STALE_MS = 5000;

export function useCanvasCollab(args: UseCanvasCollabArgs): UseCanvasCollabResult {
    const { blobId, userId, displayName, active } = args;
    const [peers, setPeers] = useState<CollabPeer[]>([]);
    const [connected, setConnected] = useState(false);
    const channelRef = useRef<RealtimeChannel | null>(null);
    // Throttle state: last-publish times + queued payloads. The published
    // value is always the freshest one — partial flushes drop intermediate
    // positions, which is what we want for cursor motion.
    const cursorLastPublishRef = useRef(0);
    const cursorQueuedRef = useRef<{ x: number; y: number } | null | undefined>(undefined);
    const cursorTimerRef = useRef<number | null>(null);
    const selectionLastPublishRef = useRef(0);
    const selectionQueuedRef = useRef<string[] | null>(null);
    const selectionTimerRef = useRef<number | null>(null);

    // Dev-only ghost peer for UI verification on a single machine. Set
    // localStorage['klypix:devCollabGhost'] = '1' (or a comma-separated
    // list of display names) in the renderer console to inject one or
    // more synthetic peers into the chip strip. Ignored in normal use —
    // no real channel traffic, no telemetry.
    const ghostPeers: CollabPeer[] = (() => {
        try {
            const raw = localStorage.getItem('klypix:devCollabGhost');
            if (!raw) return [];
            const names = raw === '1' ? ['Ghost Peer'] : raw.split(',').map(s => s.trim()).filter(Boolean);
            return names.map((name, i) => ({
                userId: `ghost_${i}`,
                deviceId: `ghost_${i}_dev`,
                displayName: name,
                color: colorForUser(`ghost_${i}`),
                lastSeen: Date.now(),
            }));
        } catch {
            return [];
        }
    })();

    useEffect(() => {
        // Collab requires: a shared canvas (blob id) + a signed-in user.
        if (!blobId || !userId) {
            setPeers([]);
            setConnected(false);
            return;
        }

        const supabase = getRealtimeClient();
        const channelName = `${CHANNEL_PREFIX}${blobId}`;
        const deviceId = getDeviceId();
        const myName = displayName || 'Anonymous';

        // Phase 12: hand the current Supabase access token to the Realtime
        // client so it can authenticate channel joins. Required once the
        // server-side channel policy flips to `private: true` (until then
        // it's a no-op for the channel but still primes the connection).
        (async () => {
            try {
                const electronAuth: any = (window as any).electron?.auth;
                const res = await electronAuth?.getAccessToken?.();
                setRealtimeAuth(res?.token ?? null);
            } catch { /* signed out / IPC missing → leave unauthenticated */ }
        })();

        // `presence: { key }` keys the presence slot. Using the per-device id
        // (not the user id) means a user with two tabs/devices appears as
        // two separate peers — accurate for the UI ("two of Sally's
        // devices are connected").
        const channel = supabase.channel(channelName, {
            config: {
                presence: { key: deviceId },
                broadcast: { self: false, ack: false },
            },
        });
        channelRef.current = channel;

        // Per-device ephemeral state (cursor + selection) accumulated from
        // broadcast events. NOT in React state directly because cursor updates
        // arrive at ~30Hz and we want a single coalesced render. Stored on a
        // Map, then merged into peers via setPeers on each presence change OR
        // broadcast tick (rAF-coalesced below).
        const ephemeralRef = new Map<string, { cursorX?: number; cursorY?: number; cursorAt?: number; selectionIds?: string[] }>();
        let renderScheduled = false;
        const scheduleRender = () => {
            if (renderScheduled) return;
            renderScheduled = true;
            requestAnimationFrame(() => {
                renderScheduled = false;
                computeAndSet();
            });
        };

        const computeAndSet = () => {
            const presenceState = channel.presenceState() as Record<string, PresenceRow[]>;
            const flat: CollabPeer[] = [];
            const now = Date.now();
            for (const slot of Object.values(presenceState)) {
                for (const row of slot) {
                    if (!row || typeof row !== 'object') continue;
                    // Skip self — UI shows OTHER peers; the user already
                    // knows they're here. Self is part of presenceState
                    // because Supabase echoes our own track() back.
                    if (row.user_id === userId && row.device_id === deviceId) continue;
                    const eph = ephemeralRef.get(row.device_id);
                    // Drop stale cursors so a peer that stopped moving doesn't
                    // leave their cursor floating forever after a network drop.
                    const cursorFresh = eph?.cursorAt && (now - eph.cursorAt) < CURSOR_STALE_MS;
                    flat.push({
                        userId: row.user_id,
                        deviceId: row.device_id,
                        displayName: row.display_name,
                        color: colorForUser(row.user_id),
                        lastSeen: now,
                        cursorX: cursorFresh ? eph?.cursorX : undefined,
                        cursorY: cursorFresh ? eph?.cursorY : undefined,
                        cursorAt: cursorFresh ? eph?.cursorAt : undefined,
                        selectionIds: eph?.selectionIds,
                    });
                }
            }
            // Clean up ephemeral entries for devices no longer in presence.
            const liveDeviceIds = new Set(Object.values(presenceState).flat().map((r: any) => r?.device_id).filter(Boolean));
            for (const k of Array.from(ephemeralRef.keys())) {
                if (!liveDeviceIds.has(k)) ephemeralRef.delete(k);
            }
            setPeers(flat);
        };
        const refreshPeers = computeAndSet;

        channel
            .on('presence', { event: 'sync' }, refreshPeers)
            .on('presence', { event: 'join' }, refreshPeers)
            .on('presence', { event: 'leave' }, refreshPeers)
            // Cursor broadcast — sent ~30Hz max per peer. Payload carries the
            // sender's device id so we can attribute it; null x/y means
            // "cursor left the canvas" → hide the remote cursor.
            .on('broadcast', { event: 'cursor' }, (msg) => {
                const p = (msg as any)?.payload;
                if (!p || typeof p.device_id !== 'string') return;
                if (p.device_id === deviceId) return; // ignore echoes (self:false already, but defensive)
                const prev = ephemeralRef.get(p.device_id) || {};
                if (p.x == null || p.y == null) {
                    // Cursor left the canvas.
                    ephemeralRef.set(p.device_id, { ...prev, cursorX: undefined, cursorY: undefined, cursorAt: undefined });
                } else {
                    ephemeralRef.set(p.device_id, { ...prev, cursorX: p.x, cursorY: p.y, cursorAt: Date.now() });
                }
                scheduleRender();
            })
            .on('broadcast', { event: 'selection' }, (msg) => {
                const p = (msg as any)?.payload;
                if (!p || typeof p.device_id !== 'string') return;
                if (p.device_id === deviceId) return;
                const prev = ephemeralRef.get(p.device_id) || {};
                ephemeralRef.set(p.device_id, { ...prev, selectionIds: Array.isArray(p.ids) ? p.ids : [] });
                scheduleRender();
            })
            .subscribe(async (status) => {
                if (status === 'SUBSCRIBED') {
                    setConnected(true);
                    // Only broadcast our presence when the tab is active.
                    // Inactive tabs still receive updates so the chip count
                    // is correct when the user returns.
                    if (active) {
                        await channel.track({
                            user_id: userId,
                            device_id: deviceId,
                            display_name: myName,
                            joined_at: Date.now(),
                        } satisfies PresenceRow);
                    }
                } else if (status === 'CHANNEL_ERROR' || status === 'TIMED_OUT' || status === 'CLOSED') {
                    setConnected(false);
                }
            });

        // Periodic stale-cursor sweep: every 2s, force a recompute so cursors
        // older than CURSOR_STALE_MS get filtered out. Without this, a peer
        // whose tab drops the network would leave their cursor frozen
        // mid-canvas indefinitely until either the channel emits a leave
        // event or new presence arrives.
        const staleInterval = window.setInterval(() => {
            // Only sweep if there's at least one peer with a cursor — saves
            // setPeers churn for the common solo case.
            let needsSweep = false;
            const now = Date.now();
            for (const eph of ephemeralRef.values()) {
                if (eph.cursorAt && (now - eph.cursorAt) >= CURSOR_STALE_MS) { needsSweep = true; break; }
            }
            if (needsSweep) computeAndSet();
        }, 2000);

        return () => {
            channelRef.current = null;
            window.clearInterval(staleInterval);
            // untrack + unsubscribe is wrapped in try/catch because the
            // channel may already be closed (network drop). Either way
            // we want to release the local handle.
            try { channel.untrack(); } catch { /* ignored */ }
            try { supabase.removeChannel(channel); } catch { /* ignored */ }
            setConnected(false);
            setPeers([]);
        };
    }, [blobId, userId, displayName, active]);

    // Throttled cursor publisher. Callers can fire on every pointermove;
    // we coalesce to at most one broadcast per CURSOR_THROTTLE_MS using
    // a leading-edge + trailing-flush pattern (fire immediately on first
    // call, queue the rest, flush once after the throttle window).
    const publishCursor = (world: { x: number; y: number } | null): void => {
        const channel = channelRef.current;
        if (!channel) return;
        cursorQueuedRef.current = world;
        const now = Date.now();
        const sinceLast = now - cursorLastPublishRef.current;
        if (sinceLast >= CURSOR_THROTTLE_MS) {
            // Leading edge: send immediately.
            cursorLastPublishRef.current = now;
            const payload = cursorQueuedRef.current;
            cursorQueuedRef.current = undefined;
            const deviceId = getDeviceId();
            channel.send({
                type: 'broadcast',
                event: 'cursor',
                payload: { device_id: deviceId, x: payload?.x ?? null, y: payload?.y ?? null },
            });
            return;
        }
        // Trailing flush: schedule a single timer to send the latest queued
        // value at the end of this throttle window.
        if (cursorTimerRef.current != null) return;
        cursorTimerRef.current = window.setTimeout(() => {
            cursorTimerRef.current = null;
            const ch = channelRef.current;
            if (!ch) return;
            cursorLastPublishRef.current = Date.now();
            const payload = cursorQueuedRef.current;
            cursorQueuedRef.current = undefined;
            const deviceId = getDeviceId();
            ch.send({
                type: 'broadcast',
                event: 'cursor',
                payload: { device_id: deviceId, x: payload?.x ?? null, y: payload?.y ?? null },
            });
        }, CURSOR_THROTTLE_MS - sinceLast);
    };

    const publishSelection = (selectionIds: string[]): void => {
        const channel = channelRef.current;
        if (!channel) return;
        selectionQueuedRef.current = selectionIds;
        const now = Date.now();
        const sinceLast = now - selectionLastPublishRef.current;
        if (sinceLast >= SELECTION_THROTTLE_MS) {
            selectionLastPublishRef.current = now;
            const ids = selectionQueuedRef.current ?? [];
            selectionQueuedRef.current = null;
            const deviceId = getDeviceId();
            channel.send({
                type: 'broadcast',
                event: 'selection',
                payload: { device_id: deviceId, ids },
            });
            return;
        }
        if (selectionTimerRef.current != null) return;
        selectionTimerRef.current = window.setTimeout(() => {
            selectionTimerRef.current = null;
            const ch = channelRef.current;
            if (!ch) return;
            selectionLastPublishRef.current = Date.now();
            const ids = selectionQueuedRef.current ?? [];
            selectionQueuedRef.current = null;
            const deviceId = getDeviceId();
            ch.send({
                type: 'broadcast',
                event: 'selection',
                payload: { device_id: deviceId, ids },
            });
        }, SELECTION_THROTTLE_MS - sinceLast);
    };

    return {
        // Ghost peers are visual-only; show them alongside whatever's
        // actually on the channel. When ghost-only (no real channel),
        // we report connected=true so the UI shows them at full opacity
        // — accurate for testing the rendered look, since "connected"
        // dimming would otherwise make every ghost chip half-faded.
        peers: ghostPeers.length > 0 ? [...peers, ...ghostPeers] : peers,
        connected: connected || ghostPeers.length > 0,
        publishCursor,
        publishSelection,
    };
}
